### ISSUE TITLE
fatal error: NSArray element failed to match the Swift Array Element type

### ISSUE THREAD

**Issue by sumdas** [DanielTomlinson/Stash#12]
let myCache = stash.objectForKey("(URL.md5)") as? UserJsonResult
print(myCache)

output message------------------
fatal error: NSArray element failed to match the Swift Array Element type

**Comment by endocrimes** [comment]
Hey! - Sorry you're experiencing this.

If it's still a problem, could you please provide me with a small sample project that reproduces the issue?

**Comment by endocrimes** [comment]
Hey! - I'm closing this issue for now, but if you provide a repro case feel free to reopen it.
